# Generated by Django 4.1.7 on 2023-03-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
